
source 'https://github.com/LiBiYong/SpecsLibrary.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'tabBarChildVCOne_Example' do
  pod 'tabBarChildVCOne', :path => '../'
pod  'ResourceUtilityClass'
end
